version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - backend

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - user_data:/var/lib/postgresql/data    
    networks:
      - backend

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
    container_name: user-service
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - user-db
    volumes:
      - ./UserService:/src/UserService
    networks:
      - backend

  kong-db:
    image: postgres:15
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - backend

  kong:
    image: kong/kong-gateway:3.6
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PASSWORD: kongadmin
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin api
      - "8002:8002"   # admin GUI (Enterprise)
    depends_on:
      - kong-db
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@edu.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    networks:
      - backend      

  angular-app:
    container_name: angular-app
    build:
      context: ./UI
      dockerfile: Dockerfile.ui
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    networks:
      - backend
    volumes:
      - ./UI:/app 

volumes:
  keycloak_data:
  kong_data:
  user_data:

networks:
  backend:
